version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - ./scraped-pages:/app/scraped-pages  # Mount the local directory for saving HTML
    env_file:
      - .env  # Optional: to anonymize or store user-specific information
    environment:
      - BASE_URL=${LETTERBOXD_PROFILE_URL}  # Pass the URL through environment variable
      - NUM_PAGES=3  # Number of pages to scrape
    command: "python scraper.py"


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - ./scraped-pages:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - scraper