version: "3.8"
services:
  scraper:
    build:
      context: .
      dockerfile: ./src/scraper/Dockerfile
    container_name: cinecriticpal_scraper
    env_file:
      - .env
    environment:
      - LETTERBOXD_USERNAME=${LETTERBOXD_USERNAME}  # Letterboxd username stored in .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: python /app/scraper/scrape.py
    networks:
      - cinecriticpal_net

  nginx:
    build:
      context: ./src/nginx
    container_name: cinecriticpal_nginx
    ports:
      - "8080:80"
    volumes:
      - ./data/html:/usr/share/nginx/html
    networks:
      - cinecriticpal_net

networks:
  cinecriticpal_net:
    driver: bridge